# Generated by Django 4.2.6 on 2023-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('credit_hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=15)),
                ('year_joined', models.CharField(max_length=5)),
                ('courses', models.ManyToManyField(to='myapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('phone_no', models.CharField(max_length=15)),
                ('year_joined', models.CharField(max_length=5)),
                ('courses', models.ManyToManyField(to='myapp.course')),
            ],
        ),
    ]
